{% set name = "oommfc" %}
{% set version = "0.8.24" %}
{% set sha256 = "35187e3656b697a64d2b73105a611fc6094251ed491bab3a2781fcd802c005bc" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  build:
    - python >=3.6
    - pip
  run:
    - python >=3.6
    - oommf ==2.0a1
    - micromagnetictests ==0.1.4
    - ubermagtable ==0.1.12

test:
  imports:
    - oommfc
  commands:
    - python -c "import sys; import oommfc as oc; sys.exit(oc.test())"

about:
  home: http://ubermag.github.io/
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: OOMMF calculator.
  doc_url: http://oommfc.readthedocs.io
  dev_url: https://github.com/ubermag/oommfc

extra:
  recipe-maintainers:
    - marijanbeg
    - takluyver
    - fangohr
