{% set name = "oommfc" %}
{% set version = "0.65.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 965bc4626e67cef2f598cb96851bc8723dc57284443e9f85615e6f8c2010f6e3

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.8
    - pip
  run:
    - python >=3.8
    - oommf ==2.0b0
    - micromagneticmodel >=0.63.2
    - micromagnetictests >=0.63.1
    - ubermagtable >=0.61.3
    - ubermagutil >=0.63.2
    - micromagneticdata >=0.65.1

test:
  imports:
    - oommfc
  commands:
    - python -c "import sys; import oommfc; sys.exit(oommfc.test())"

about:
  home: http://ubermag.github.io/
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: OOMMF calculator.
  doc_url: https://ubermag.github.io/documentation/oommfc.html
  dev_url: https://github.com/ubermag/oommfc

extra:
  recipe-maintainers:
    - marijanbeg
    - takluyver
    - fangohr
    - lang-m
    - samjrholt
    - swapneelap
