{% set name = "oommfc" %}
{% set version = "0.8.13" %}
{% set sha256 = "185c1c62a4e14e45898ca0e915d97e066ad915b8b92ddf225761417678537c96" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  number: 0
  script: pip install --no-deps . -vvv

requirements:
  build:
    - python >=3.6
    - pip
  run:
    - python >=3.6
    - scipy
    - micromagneticmodel
    - ubermagtable
    - oommf
    - pytest
    - testpath

test:
  imports:
    - oommfc

  commands:
    - python -c "import sys; import oommfc as m; sys.exit(m.test())"

about:
  home: http://ubermag.github.io/
  license: BSD-3-clause
  summary: Python interface to OOMMF integrated into Jupyter notebook.
  license_family: BSD
  license_file: LICENSE

  description: |
    `oommfc` is a Python package that provides:

    - An interface to the Object Oriented MicroMagnetic Framework OOMMF
    - Integration of OOMMF simulations into the Jupyter notebook

    It is available on all major operating systems (Windows, MacOS, Linux) and requires Python 3.6 or higher.
  doc_url: http://oommfc.readthedocs.io
  dev_url: https://github.com/ubermag/oommfc

extra:
  recipe-maintainers:
    - marijanbeg
    - fangohr
    - takluyver
