{% set name = "oommfc" %}
{% set version = "0.9" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 05e8b9eea83ac75d7f944c4d4b1d0ad99b27ccfb7da060a47c0eb87761dbda98

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.8
    - pip
  run:
    - python >=3.8
    - oommf ==2.0a1
    - micromagnetictests ==0.1.8
    - ubermagtable ==0.3

test:
  imports:
    - oommfc
  commands:
    - python -c "import sys; import oommfc; sys.exit(oommfc.test())"

about:
  home: http://ubermag.github.io/
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: OOMMF calculator.
  doc_url: http://oommfc.readthedocs.io
  dev_url: https://github.com/ubermag/oommfc

extra:
  recipe-maintainers:
    - marijanbeg
    - takluyver
    - fangohr
    - lang-m
