{% set name = "oommfc" %}
{% set version = "0.60.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: cac2b96f4110e9cfd7b0e98b6208828d62b89c5c7c16e6bbf72eb2a9e0b48556

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.8
    - pip
  run:
    - python >=3.8
    - oommf ==2.0a2
    - micromagnetictests >=0.60.0,<0.61.0
    - ubermagtable >=0.60.0,<0.61.0

test:
  imports:
    - oommfc
  commands:
    - python -c "import sys; import oommfc; sys.exit(oommfc.test())"

about:
  home: http://ubermag.github.io/
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: OOMMF calculator.
  doc_url: https://ubermag.github.io/documentation/oommfc.html
  dev_url: https://github.com/ubermag/oommfc

extra:
  recipe-maintainers:
    - marijanbeg
    - takluyver
    - fangohr
    - lang-m
    - samjrholt
