{% set name = "oommfc" %}
{% set version = "0.61.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: b04db14d8404e4d5fd1a9c3a3e4be51d3625a491ffe1cbdc8ab05008f435154d

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.8
    - pip
  run:
    - python >=3.8
    - oommf ==2.0a3
    - micromagnetictests >=0.61.0,<0.62.0
    - ubermagtable >=0.61.0,<0.62.0
    - micromagneticdata >=0.61.0,<0.62.0

test:
  imports:
    - oommfc
  commands:
    - python -c "import sys; import oommfc; sys.exit(oommfc.test())"

about:
  home: http://ubermag.github.io/
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: OOMMF calculator.
  doc_url: https://ubermag.github.io/documentation/oommfc.html
  dev_url: https://github.com/ubermag/oommfc

extra:
  recipe-maintainers:
    - marijanbeg
    - takluyver
    - fangohr
    - lang-m
    - samjrholt
    - swapneelap
