{% set name = "oommfc" %}
{% set version = "0.8.10" %}
{% set sha256 = "d9b6ea2973c7e97633f7a2257893296611e95cf27c1fd3f2448b29f135ef48f9" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  number: 0
  script: pip install --no-deps .

requirements:
  build:
    - python >=3.6
    - pip
  run:
    - python >=3.6
    - scipy
    - micromagneticmodel
    - oommfodt
    - oommf
    - pytest
    - testpath

test:
  imports:
    - oommfc

  commands:
    - python -c "import sys; import oommfc as m; sys.exit(m.test())"

about:
  home: http://joommf.github.io/
  license: BSD 3-clause
  summary: A Python interface to the OOMMF micromagnetic calculator
  license_family: BSD
  license_file: LICENSE

  description: |
    The OOMMF Calculator (OOMMFC) is a calculator for the numerical
    operations required for micromagnetic calculations. Technically,
    the OOMMFC class inherits from the "micromagneticmodel", which is
    an abstract description of a micromagnetic problem.

    Another way of describing OOMMFC is that it provides a Python
    interface to the OOMMF micromagnetic package from NIST.

  doc_url: http://oommfc.readthedocs.io
  dev_url: https://github.com/joommf/oommfc

extra:
  recipe-maintainers:
    - marijanbeg
    - fangohr
    - takluyver
    - rpep
    - davidcortesortuno
