{% set name = "oommfc" %}
{% set version = "0.63.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 867b1aaefe73044ec3d3a36b32cc5b1550a4441d793797ef324fa44d558e1dc9

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.8
    - pip
  run:
    - python >=3.8
    - oommf ==2.0a3
    - micromagneticmodel >=0.62.0
    - micromagnetictests >=0.62.0
    - ubermagtable >=0.61.1
    - ubermagutil >=0.63.0
    - micromagneticdata >=0.63.0

test:
  imports:
    - oommfc
  commands:
    - python -c "import sys; import oommfc; sys.exit(oommfc.test())"

about:
  home: http://ubermag.github.io/
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: OOMMF calculator.
  doc_url: https://ubermag.github.io/documentation/oommfc.html
  dev_url: https://github.com/ubermag/oommfc

extra:
  recipe-maintainers:
    - marijanbeg
    - takluyver
    - fangohr
    - lang-m
    - samjrholt
    - swapneelap
