{% set name = "oommfc" %}
{% set version = "0.8.14" %}
{% set sha256 = "c24fdd7446080490e3ab5e8a67db17b94627b8a8fe94e00bc012e732de5077c1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  build:
    - python >=3.6
    - pip
  run:
    - python >=3.6
    - oommf
    - scipy
    - micromagneticmodel
    - ubermagtable

test:
  imports:
    - oommfc
  commands:
    - python -c "import sys; import oommfc as oc; sys.exit(oc.test())"

about:
  home: http://ubermag.github.io/
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: OOMMF calculator.
  doc_url: http://oommfc.readthedocs.io
  dev_url: https://github.com/ubermag/oommfc

extra:
  recipe-maintainers:
    - marijanbeg
    - fangohr
    - takluyver
