{% set name = "oommfc" %}
{% set version = "0.8.13" %}
{% set sha256 = "185c1c62a4e14e45898ca0e915d97e066ad915b8b92ddf225761417678537c96" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  number: 0
  script: pip install --no-deps . -vvv

requirements:
  build:
    - python >=3.6
    - pip
  run:
    - python >=3.6
    - oommf
    - scipy
    - micromagneticmodel
    - ubermagtable

test:
  imports:
    - oommfc
    - oommfc.oommf
    - oommfc.examples

  commands:
    - python -c "import sys; import oommfc as oc; sys.exit(oc.test())"

about:
  home: http://ubermag.github.io/
  license: BSD-3-clause
  license_family: BSD
  license_file: LICENSE
  summary: OOMMF calculator.
  doc_url: http://oommfc.readthedocs.io
  dev_url: https://github.com/ubermag/oommfc

  description: |
  `oommfc` is a Python package that provides:
    - An Object Oriented MicroMagnetic Framework OOMMF calculator for driving micromagnetic systems defined using micromagneticmodel.

extra:
  recipe-maintainers:
    - marijanbeg
    - fangohr
    - takluyver
