{% set name = "oommfc" %}
{% set version = "0.64.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: c64c963d62b7758b2bad5a43dc6b0a12d2112f64c3a2d93d5635ddaa5032f9f9

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.8
    - pip
  run:
    - python >=3.8
    - oommf ==2.0b0
    - micromagneticmodel >=0.63.0
    - micromagnetictests >=0.63.0
    - ubermagtable >=0.61.1
    - ubermagutil >=0.63.0
    - micromagneticdata >=0.65.0

test:
  imports:
    - oommfc
  commands:
    - python -c "import sys; import oommfc; sys.exit(oommfc.test())"

about:
  home: http://ubermag.github.io/
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: OOMMF calculator.
  doc_url: https://ubermag.github.io/documentation/oommfc.html
  dev_url: https://github.com/ubermag/oommfc

extra:
  recipe-maintainers:
    - marijanbeg
    - takluyver
    - fangohr
    - lang-m
    - samjrholt
    - swapneelap
