# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yml and/or the recipe/meta.yaml.
# -*- mode: yaml -*-

language: generic

os: osx
osx_image: xcode9.4


env:
  matrix:
    - CONFIG=osx_

  global:
    # The BINSTAR_TOKEN secure variable. This is defined canonically in conda-forge.yml.
    - secure: "VshdTqqIaKVf0bGqCu4gGgMcHa/JZyVfDFiVgrkli4ErZGW0clUWE3THFB0Yh4DfHFGr6xmGQo4BJPF0RcXdwwjtGMXUaSm8dPBAhYyetmS1oAkcg9JJ8000aXjSJjtb2vTX12lwLhKRzegdqNFYusaUiiLqA+8dS6LOP5cWjeu4gjvQK1ZLKrFEs5wG+2GvNxR0vWe87BAJCAyb8/7xW8roEE5hrxHgEJls2kyN0y11ryzC7rL5c42wnUbwRclx888Ikq1T2VoZ04f4W244A7kXlon0sjD7pD2VU5HCvab7J4Qa++jEj+GeqUaoimCJV0Has/Pj8D6yHRpoBZT0Svs9Svq/YJIVYJRTLHupidtDoN4fy6OMsBSyavOfrWssBbHiHk++x6nNC9a+cBXTvtfe1qTv4DOL73/LNGgtdKqOTjwSqFrlL7aA1wGkNOyt5W9Z41vmPjZLBbCwBGmSYeooJj3hDrpMPL3TO5ccBrHdcp659/JoHmZnGdN1OV/8QaVJFKL9QfCXMROqoOMQWcWvYaUnMkgp5tSlUI808q+gX/ENv2umQ8QmQnYYk99SA3dFoMszIL2SktTKSSAwSI0agNqzTt8o7Mxf9gReXrhyUHARrB5UHFN8Qlp6np3g50ac81YvsESceDJ9AuSjOo8J7CDBjsqxg4wQNb0Z0qA="


before_install:
    # Fast finish the PR.
    - |
      (curl https://raw.githubusercontent.com/conda-forge/conda-forge-ci-setup-feedstock/master/recipe/conda_forge_ci_setup/ff_ci_pr_build.py | \
          python - -v --ci "travis" "${TRAVIS_REPO_SLUG}" "${TRAVIS_BUILD_NUMBER}" "${TRAVIS_PULL_REQUEST}") || exit 1

    # Remove homebrew.
    - |
      echo ""
      echo "Removing homebrew from Travis CI to avoid conflicts."
      curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/uninstall > ~/uninstall_homebrew
      chmod +x ~/uninstall_homebrew
      ~/uninstall_homebrew -fq
      rm ~/uninstall_homebrew


install:
    # Install Miniconda.
    - |
      echo ""
      echo "Installing a fresh version of Miniconda."
      MINICONDA_URL="https://repo.continuum.io/miniconda"
      MINICONDA_FILE="Miniconda3-latest-MacOSX-x86_64.sh"
      curl -L -O "${MINICONDA_URL}/${MINICONDA_FILE}"
      bash $MINICONDA_FILE -b

    # Configure conda.
    - |
      echo ""
      echo "Configuring conda."
      source /Users/travis/miniconda3/bin/activate root

      conda install -n root -c conda-forge --quiet --yes conda-forge-ci-setup=2 conda-build
      setup_conda_rc ./ ./recipe ./.ci_support/${CONFIG}.yaml

      source run_conda_forge_build_setup

    # compiler cleanup
    - |
      mangle_compiler ./ ./recipe ./.ci_support/${CONFIG}.yaml

script:
  # generate the build number clobber
  - make_build_number ./ ./recipe ./.ci_support/${CONFIG}.yaml
  -  conda build ./recipe -m ./.ci_support/${CONFIG}.yaml --clobber-file ./.ci_support/clobber_${CONFIG}.yaml
  - upload_package ./ ./recipe ./.ci_support/${CONFIG}.yaml