travis:
  secure:
    BINSTAR_TOKEN: VshdTqqIaKVf0bGqCu4gGgMcHa/JZyVfDFiVgrkli4ErZGW0clUWE3THFB0Yh4DfHFGr6xmGQo4BJPF0RcXdwwjtGMXUaSm8dPBAhYyetmS1oAkcg9JJ8000aXjSJjtb2vTX12lwLhKRzegdqNFYusaUiiLqA+8dS6LOP5cWjeu4gjvQK1ZLKrFEs5wG+2GvNxR0vWe87BAJCAyb8/7xW8roEE5hrxHgEJls2kyN0y11ryzC7rL5c42wnUbwRclx888Ikq1T2VoZ04f4W244A7kXlon0sjD7pD2VU5HCvab7J4Qa++jEj+GeqUaoimCJV0Has/Pj8D6yHRpoBZT0Svs9Svq/YJIVYJRTLHupidtDoN4fy6OMsBSyavOfrWssBbHiHk++x6nNC9a+cBXTvtfe1qTv4DOL73/LNGgtdKqOTjwSqFrlL7aA1wGkNOyt5W9Z41vmPjZLBbCwBGmSYeooJj3hDrpMPL3TO5ccBrHdcp659/JoHmZnGdN1OV/8QaVJFKL9QfCXMROqoOMQWcWvYaUnMkgp5tSlUI808q+gX/ENv2umQ8QmQnYYk99SA3dFoMszIL2SktTKSSAwSI0agNqzTt8o7Mxf9gReXrhyUHARrB5UHFN8Qlp6np3g50ac81YvsESceDJ9AuSjOo8J7CDBjsqxg4wQNb0Z0qA=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
