travis:
  secure:
    BINSTAR_TOKEN: KRhs5CwqYE1fLnCirwLdzwyn7K72Zp7zbUWBmF7pKjFXUWfbyssbyeZ7DxwqyFf9g/cUQ2BejE6mrqKmiFiwcEiJMovIF+FRgUkvG9uzJqjnQWylTnS93xrc8Q4xBnZ4vl80akM8OROTRm6Mc6ZmNQVAArSTBJJcNsOso76L2eOSDtMfYTP5842XCuisx3RB5hPRivCRThomjQQP6dAwNkl9FSGorM/HGvvucstUX+hfuOFKikF1TLMphtRgdqRkeqbli8iqvafXjgf6ka5RffDilofdLLvtjkoM8M9hB2V81RXwsHqd1costNg9DahOLxbIfRf9o6+B168i+UdqqzvBn1jvphWPik5dU3iKrCI+E/paac4Bb7JlWQ8U7Hq+IKsVvDWGcCeW4GARdahTWAj7GPxcha5YLpelIf4rXMOusrI3Oae1OMPAVhmKJJ7EaWudbFG8q2rLYQVsQoXNFz2YSzdf/JW1oDiWmmtu4wRc8Ocbwoy7z+z5fEKu3GQLNX3+VNJpiXcq++TuE8BkyileririnS9AcjGV/8LWYsH9Ln8yuSxAIV3Ygw70KVT5ZDXtuWDZthxEJegZG+BAHn/f+SGAVOWxZu66PUa4d2PpDS5Oo2b9+AwzOK+Gs+0kN5koppOMydCyHWd5fbVzOEvfTh17xmZBRVEJw82STUo=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
